buildscript {
    ext.kotlin_version = '1.9.24'
    repositories {
        maven {
            url "https://maven.aliyun.com/repository/google"
            allowInsecureProtocol = true
        }
        maven {
            url "https://maven.aliyun.com/repository/central"
            allowInsecureProtocol = true
        }
        maven {
            url "http://maven.aliyun.com/nexus/content/groups/public"
            allowInsecureProtocol = true
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    }
}

allprojects {
    repositories {
        maven {
            url "https://maven.aliyun.com/repository/google"
            allowInsecureProtocol = true
        }
        maven {
            url "https://maven.aliyun.com/repository/central"
            allowInsecureProtocol = true
        }
        maven {
            url "http://maven.aliyun.com/nexus/content/groups/public"
            allowInsecureProtocol = true
        }
    }
}