buildscript {
    ext.kotlin_version = '1.9.24'
    ext.gdx_version = '1.11.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    }
}

ext {
    appVersionName = '0.7.2'
    appVersionCode = 51
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
