apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions.jvmTarget = '1.8'
}

sourceSets {
    main {
        java.exclude 'com/egoal/darkestpixeldungeon/android/**'
        resources.srcDir 'src/main/assets'
    }
}

processResources {
    from('src/main/java') { include '**/*.properties' }
}

dependencies {
    api project(':SPD-classes')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
}
